### ISSUE TITLE
Yarn docs noted as out of date use old url

### ISSUE THREAD

**Issue by TheMartianLife** [JujuAdams/Chatterbox#113]
Great job with Chatterbox!

Your docs do a great job of covering Yarn Syntax, but note that the Yarn docs from Yarn Spinner are out of date and have been for some time ([page link](https://www.jujuadams.com/Chatterbox/#/2.18/concept-yarn-script)). This is because the url used is explicitly to the v1 docs; the newer docs since v2 live at ([docs.yarnspinner.dev](https://docs.yarnspinner.dev/beginners-guide/syntax-basics)) and include great resources such as the online editor Try Yarn Spinner in which people can practice writing and testing their scripts.

At the same time, we are about to release Yarn v3 in the coming weeks and this includes further syntax additions. These might interest you or your users as potential additions to Chatterbox: [yarnspinner.dev/v3](https://yarnspinner.dev/v3).

If there’s anything we can ever help with as far as docs or resources or info about Yarn core goes, do get in touch! Our Discord has a healthy channel of other Yarn tool maintainers, where we discuss bug fixes and user questions and upcoming changes to the language 💚

**Comment by JujuAdams** [comment]
Thank you for reaching out. I will remove that dead link. I will further be removing references to Yarn in the coming weeks to avoid deepening confusion.

Chatterbox was written as an implementation of an early version of the v2 YarnScript spec from 2020. I've never done a great job at explaining how Chatterbox and Yarn differ. Chatterbox and Yarn have diverged sufficiently (Chatterbox organically grew to accommodate roughly half of the features in Yarn v3) that bringing them back in line would require many hours of (unpaid) work and automatically constitutes a major breaking version change. This isn't attractive and so an "unhooking" of the two solutions is the most straight-forward solution.

I would have liked to participate in Yarn more and I was indeed on your Discord server and offered a lot of feedback on the YarnScript v2 spec. Sadly, support for other engines was not respected at that time. When I expressed a desire to firm up the YarnScript specification so I could make a proper implementation, I was told in so many words to fuck off because I didn't contribute fixes to the YarnSpinner Unity repo.

That short-sighted approach seems to have given way, however. The team looks to be engaged on getting things working in other engines. There is always more room for narrative tools and I would be happy to forward people to Yarn Spinner channels where that's helpful ([in docs](https://www.jujuadams.com/Chatterbox/#/2.18/Alternatives) and in the README). Please contact me again when you have a GameMaker repo set up and I can make the necessary adjustments.

**Comment by TheMartianLife** [comment]
We’re happy to help any way we can. I’m sorry that was your experience - though it was a bit before my time and I can’t see anything to that effect in our Discord history. I know attempts to make a spec in the past have been fraught; somewhat because the Yarn ecosystem was already so fragmented and heterogeneous when we inherited it, and the team felt it was not our place to effectively deprecate or de-canonise other people’s things that were already out in the wild by making them non-compliant. But primarily because we’re just four people who do this mostly unpaid - so we are often forced to focus on just the engines/resources/services we can provide well. I’m sure you know how Open Source is.

Any efforts to make our tools either more consistent or more conceptually separate over the coming months  _is effort_ on your part,  and we are happy to give some of ours if you would like it. You’re always welcome in our Discord and other places, either way, as are your users - we do already try to keep across your docs and help them whenever they pop up in our Discord or web/social media alerts.

Feel free to reach out 💚
