### ISSUE TITLE
Yarn $variables do not autodeclare when using <<set ... to ...>>

### ISSUE THREAD

**Issue by realDragon11** [JujuAdams/Chatterbox#58]
`
Chatterbox:
Trying to set Yarn variable $PestleInCamp but it has not been declared`
with Yarn
`<<set $PestleInCamp to 1>>`
Version: 2.2.2, 2022-01-09
IDE: latest beta

**Comment by JujuAdams** [comment]
Thanks for reporting this, I'll take a look when I can. For other users encountering this bug, please use `ChatterboxVariableDefault()` to work around the issue.

**Comment by ThePounceThatWasPromised** [comment]
For those who wish to be able to maintain the ability to set\declare parameters directly from the yarn the script a way to workaround this issue is to edit the "ChatterboxVariable" script file, find the place where it says "if (CHATTERBOX_ERROR_UNDECLARED_VARIABLE) and inside the else statement add the line "ChatterboxVariableDefault(_name,_value);". 

With this change it will allow setting variables from the script.

**Comment by JujuAdams** [comment]
Fixed https://github.com/JujuAdams/Chatterbox/commit/bf30e8755b6682cbf4fc0738763301fda9ad64ea

Another one of those situations where the YarnScript specification is vague, incomplete, and has not been updated to reflect what's happening in the canonical Unity implementation to which the rest of their documentation is written. One can only hope that their Epic Grant will stimulate some action on this front.

Please note that Chatterbox will still throw an error if you try to read an unset variable.
